name: Add Movie to List

on:
  issues:
    types: [opened]

jobs:
  update-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install Dependencies
        # Added beautifulsoup4 to allow scraping letterboxd
        run: pip install requests beautifulsoup4
        
      - name: Run Update Script
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: python scripts/update_list.py
        
      - name: Commit and Push changes
        run: |
          git config --global user.name "Movie-Bot"
          git config --global user.email "bot@github.com"
          git add data/movies.json
          
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automated: Add movie from issue #${{ github.event.issue.number }}" && git push)
